// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANy56f2yf3W9R4s_12nnEsQuxampyB6W4',
    appId: '1:564162919982:web:8e2da7f72fad3bbe3429bf',
    messagingSenderId: '564162919982',
    projectId: 'dalel-6fdeb',
    authDomain: 'dalel-6fdeb.firebaseapp.com',
    storageBucket: 'dalel-6fdeb.appspot.com',
    measurementId: 'G-FCC3XW2EJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLn0_UdX06pfCoZo2ds3BCQKlLIcI1_Kk',
    appId: '1:564162919982:android:637bdbbd7b3cc8673429bf',
    messagingSenderId: '564162919982',
    projectId: 'dalel-6fdeb',
    storageBucket: 'dalel-6fdeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfkn5V1EU4KWRAzOHkldvJA3PRlwLrurY',
    appId: '1:564162919982:ios:d5a541549f00c0403429bf',
    messagingSenderId: '564162919982',
    projectId: 'dalel-6fdeb',
    storageBucket: 'dalel-6fdeb.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfkn5V1EU4KWRAzOHkldvJA3PRlwLrurY',
    appId: '1:564162919982:ios:9e9f763e339122c63429bf',
    messagingSenderId: '564162919982',
    projectId: 'dalel-6fdeb',
    storageBucket: 'dalel-6fdeb.appspot.com',
    iosBundleId: 'com.example.dalel.RunnerTests',
  );
}
